export const PRODUCT_GET_SUCCESS = 'PRODUCT_GET_SUCCESS';
export const PRODUCT_GET_START = 'PRODUCT_GET_START';
export const PRODUCT_GET_ERROR = 'PRODUCT_GET_ERROR';

export const PRODUCT_CHANGE_PAGE = 'PRODUCT_CHANGE_PAGE';
