export const PRODUCTS_GET_SUCCESS = 'PRODUCTS_GET_SUCCESS';
export const PRODUCTS_GET_START = 'PRODUCTS_GET_START';
export const PRODUCTS_GET_ERROR = 'PRODUCTS_GET_ERROR';

export const PRODUCTS_CHANGE_PAGE = 'PRODUCTS_CHANGE_PAGE';
export const PRODUCTS_CHANGE_QUANTITY = 'PRODUCTS_CHANGE_QUANTITY';
